### ISSUE TITLE
Invalid token auth relm error when running "docker login" 

### ISSUE THREAD

**Issue by Nick-Harvey** [SUSE/caasp-services#24]
Good Morning, 

When launching the chart with ingress ssl enabled (using the Silly account), and then trying to log into the docker registry via the command line, you get the following: 

> Error response from daemon: Get https://foo.bar.com/v2/: invalid token auth challenge realm: parse http://reg-portus-nginx:%!s(<nil>)/v2/token: invalid URL escape "%!s"

New to helm in general, but my suspicion is that it's a formatting issue in the glob in the registry-configmap: 

```
data:
  {{- if .Values.portus.tls.enabled }}
  REGISTRY_AUTH_TOKEN_REALM: {{ printf "https://%s:%s/v2/token" (.Values.nginx.host | default (printf "%s" (include "nginx.fullname" .))) .Values.nginx.port | quote }}
  REGISTRY_AUTH_TOKEN_SERVICE: {{ printf "%s:%s" (include "registry.fullname" .) .Values.registry.service.port | quote }}
  REGISTRY_AUTH_TOKEN_ISSUER: {{ template "portus.fullname" . }}
  REGISTRY_HTTP_TLS_KEY: "/certificates/portus.key"
  REGISTRY_HTTP_TLS_CERTIFICATE: "/certificates/portus.crt"
  REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: "/certificates/portus.crt"
  {{- else }}
  REGISTRY_AUTH_SILLY_REALM: {{ printf "http://%s:%s/v2/token" (.Values.nginx.host | default (printf "%s" (include "nginx.fullname" .))) (.Values.nginx.service.nodePort | default .Values.nginx.port) | quote }} 
  REGISTRY_AUTH_SILLY_SERVICE: {{ printf "%s:%s" (include "registry.fullname" .) .Values.registry.service.port | quote }}
  {{- end }}

  REGISTRY_STORAGE_PROVIDER: gcs
  REGISTRY_STORAGE_BUCKET: kube-devregistry
  REGISTRY_HTTP_SECRET: Daedalus

  REGISTRY_NOTIFICATIONS_ENDPOINTS: >
```
--- Update 1
Looks like the env variable is getting set incorrectly

```
# env | grep -i token
REGISTRY_AUTH_SILLY_REALM=http://reg-portus-nginx:%!s(<nil>)/v2/token
```
